name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["dev"]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
          && npm run lint:fix

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install --legacy-peer-deps
          && npm run build
